name: Deploy to Supabase

on:
  push:
    branches:
      - main
    paths:
      - 'supabase-schema.sql'
      - '.github/workflows/deploy-supabase.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase Project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          echo "Linking to Supabase project: ${{ secrets.SUPABASE_PROJECT_ID }}"
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --password "${{ secrets.SUPABASE_DB_PASSWORD }}"

      - name: Apply database schema
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          echo "Applying database schema via Supabase CLI..."
          echo "Note: CLI automatically handles IPv4/IPv6 compatibility via Supavisor"
          
          # Apply schema using Supabase CLI (handles IPv6 → IPv4 routing automatically)
          supabase db execute --file supabase-schema.sql --password "${{ secrets.SUPABASE_DB_PASSWORD }}"

      - name: Verify deployment
        run: |
          echo "✅ Database schema applied successfully!"
          echo "   Tables created: contacts, agents, conversations, messages, bookings, settings,"
          echo "   customer_analytics, waitlist, questionnaires, reviews, and more."
