name: Deploy to Supabase

on:
  push:
    branches:
      - main
    paths:
      - 'supabase-schema.sql'
      - '.github/workflows/deploy-supabase.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply database schema via Supavisor (IPv4-compatible)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          # Install PostgreSQL client
          sudo apt-get update -qq && sudo apt-get install -y postgresql-client
          
          echo "Connecting via Supavisor pooler (IPv4-compatible)..."
          echo "Using separate params to avoid URL encoding issues with special characters"
          
          # Use Supavisor pooler with separate parameters (no URL encoding needed!)
          # Port 6543 = Transaction mode pooler
          psql \
            -h "aws-0-eu-west-1.pooler.supabase.com" \
            -p 6543 \
            -U "postgres.${SUPABASE_PROJECT_ID}" \
            -d postgres \
            -f supabase-schema.sql

      - name: Verify deployment
        run: |
          echo "✅ Database schema applied successfully!"
          echo "   Tables created: contacts, agents, conversations, messages, bookings, settings,"
          echo "   customer_analytics, waitlist, questionnaires, reviews, and more."
